### ISSUE TITLE
[Maven Plugin] Add 'start' goal

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/zed#35]

**Comment by hekonsek** [comment]
@ajurasz In case you're bored... :) I wanted to add `mvn zed:deploy-start -DdeployableId=foo` and `mvn zed:deploy-start-all` goals. We already have shell commands for those, now we need to create a Maven goals. With these two commands, we can not only deploy but run our deploeyables.

Just saying :) .

**Comment by ajurasz** [comment]
Will do.

**Comment by hekonsek** [comment]
Resolved by #63.
