### ISSUE TITLE
DefaultProcessExecutor should check if deployable isn't already running

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/zed#59]
That will solve  the problem with long running processes, like database servers. Simple as that - if you started MongoDB server, then executing `mvn zed:deploy-start-all` or `mvn zed:deploy-start` won't attempt to start new server instance.

That do you think @ajurasz ?

**Comment by ajurasz** [comment]
This check seems to be reasonable if it comes to MongoDB.

**Comment by hekonsek** [comment]
Actually I think this rule can apply to all started deployables. For example started fat jar process should not be restarted nor started twice as well.

**Comment by hekonsek** [comment]
Resolved by #70.
