### ISSUE TITLE
MongoDB handler should provide default run options

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/zed#60]
The final command executed should look like:

    docker run --name mongodb -v /var/zed/mongodb/default:/data/db -p 27017:27017 -t dockerfile/mongodb

This way data is always in the same location (`/var/zed/mongodb/default`) and `mongodb:27017` address name can be used by other Docker containers to access MongoDB server when linking them together.

**Comment by hekonsek** [comment]
@ajurasz Anything else we should add by default?

**Comment by ajurasz** [comment]
For now, this should be enough.

**Comment by hekonsek** [comment]
Resolved.
