### ISSUE TITLE
Docker containers should be created in the deployment handler

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/zed#66]
Currently we create and start container in execution handler. This is invalid approach - containers should be created in deployment handler. Execution handler should only execute container with the existing PID (which has been created on in deployment phase).

**Comment by hekonsek** [comment]
@ajurasz BTW This one might be interesting for you. Just saying, if you have some spare time and wanna make our Docker deplyables better :) .

**Comment by ajurasz** [comment]
@hekonsek sure, will do.

**Comment by hekonsek** [comment]
@ajurasz Can you consider resolving this one before we proceed to the #81? I'd like to close 0.0.18 and release version before that.

**Comment by ajurasz** [comment]
@hekonsek ok

**Comment by hekonsek** [comment]
Resolved by #82.
