### ISSUE TITLE
Deploy fatjars via ssh

### ISSUE THREAD

**Issue by ajurasz** [hekonsek/zed#86]
Enhance fatjar uri to support ssh parameters:

<code>fatjar:mvn:com.github.zed-platform/zed-service-document-mongo/0.0.18/war?ssh-host=127.0.0.1&ssh-user=foo&ssh-password=bar</code>*

so when all ssh-* params will be set we will do <code>scp</code> of downloaded <code>fatjar</code> to  remote host.

*to protect password we can use placeholders <code>${password}</code>

**Comment by ajurasz** [comment]
Finall URI:

fatjar:mvn:com.github.zed-platform/zed-service-document-mongo/0.0.18/war?ssh-host=127.0.0.1&ssh-user=foo&ssh-password=bar[&ssh-port=10022]

**Comment by hekonsek** [comment]
It's in progress or done? :)

**Comment by ajurasz** [comment]
Done.

**Comment by hekonsek** [comment]
Cool. I'm gonna test it today with the camelm2m-shell :) .

**Comment by ajurasz** [comment]
Great, in case it won't work please reopen this issue.
